name: MCRNNOC
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics=2019.1.0
  - scipy=1.14.0
  - numpy=1.26.4
  - matplotlib=3.8.4
  - dolfin-adjoint=2023.0.0
  - python=3.12.4
  - pip=24.0
  - pip:
      - https://zenodo.org/records/10644778/files/milzj/FW4PDE-v1.0.2.zip?download=1

